# Changes here will be overwritten by Copier
_commit: v2
_src_path: git+https://github.com/WaylonWalker/markata-blog-starter
author_email: null
author_fullname: Hall Block
author_twitter: '@'
description: A blog created from the markata blog-starter
project_name: My Blog
python_package_import_name: my_blog
url: https://mrparoxysms.github.io/my-blog

