[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my_blog"

description = "A blog created from the markata blog-starter"

readme = "README.md"
requires-python = ">=3.7"
license = "MIT"


# authors = [
#   { name = "Hall Block", email = "None" },
# ]


dependencies = ['markata~=0.5.0.dev0']
dynamic = ["version"]

[tool.hatch.version]
path = "my_blog/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "pyinstrument",
]

[tool.hatch.envs.default.scripts]
clean = "markata clean"
build = "markata build"
tui = "markata tui"
serve = "python -m http.server 8000 --directory=markout"
clean-build = ['clean', 'build',]
clean-tui = ['clean', 'build', 'tui']
